# Generated by Django 3.1.5 on 2021-01-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
