# Generated by Django 3.1.5 on 2021-01-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_evolution_evolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hp', 'Hp'), ('attack', 'Attack'), ('defense', 'Defense'), ('special_attack', 'SpecialAttack'), ('special_defense', 'SpecialDefense'), ('speed', 'Speed')], default='hp', max_length=18)),
                ('base_stat', models.FloatField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pokemon')),
            ],
        ),
    ]
