# Generated by Django 3.1.5 on 2021-01-25 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.pokemon'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='type',
            field=models.CharField(max_length=18),
        ),
    ]
